# ==============================================================================
# PLR THEOREM - TEST 6 (Corrected v1.1): Analytic Generalization
#
# NEW RESEARCH FRONTIER: APPLICATION 2 - THE PRIME GAP PROBLEM
#
# CORRECTION (v1.1):
# - The regular expression parser has been improved to correctly
#   find and read the "Density Trend Check" table from your
#   'PLR_TPC-result.txt' file.
#
# GOAL:
# To find the "Constant of Proportionality" (C_2) by calculating:
# Constant = Measured_Density / (1 / (ln N)^2)
# ==============================================================================

import time
import math
import re
import os # Added to check file existence

# --- Configuration ---
# This is the file generated by our 100% accurate v23.0 engine.
INPUT_FILE = "../Result/PLR_TPC-result.txt"

# This is the (simplified) theoretical density function for twin primes
def get_theoretical_density_base(n):
    """Returns the theoretical density base: 1 / (ln(n))^2"""
    if n <= 1:
        return 0
    log_n = math.log(n) # ln(N)
    return 1 / (log_n * log_n)

# --- Main Testing Logic ---
def run_analytic_generalization():
    
    print(f"\nStarting PLR Analytic Generalization (Test 6 Corrected)...")
    print(f"  - Loading data from '{INPUT_FILE}'")
    
    if not os.path.exists(INPUT_FILE):
        print(f"FATAL ERROR: The input file '{INPUT_FILE}' was not found.")
        print("Please ensure 'PLR_TPC-result.txt' is in the same folder.")
        return

    try:
        with open(INPUT_FILE, 'r') as f:
            content = f.read()
    except Exception as e:
        print(f"FATAL ERROR: Could not read file: {e}")
        return
        
    # --- Parse the "Density Trend Check" table ---
    
    # *** THIS IS THE CORRECTED REGEX (v1.1) ***
    # It now looks for the *actual table header* ("N Gaps | Twin Density..."),
    # then the '----' line, then captures the data block.
    table_regex = re.compile(
        r"N Gaps\s+\|\s+Twin Density \(g_n=2\).*?\n(-*?)\n(.*?)\n\n",
        re.DOTALL | re.MULTILINE
    )
    # This data regex is still correct.
    data_regex = re.compile(r"([\d,]+)\s*\|\s*([\d\.]+)\s*\|\s*([\d\.]+)")
    
    table_match = table_regex.search(content)
    if not table_match:
        print("FATAL ERROR: Could not find the 'Density Trend Check' table in the result file.")
        print("The regex parser failed. File format might be different than expected.")
        return
        
    # Get the block of text containing only the data rows
    data_block = table_match.group(2).strip()
    
    analysis_data = []
    for row in data_block.split('\n'):
        match = data_regex.match(row.strip())
        if match:
            n_gaps = int(match.group(1).replace(',', ''))
            twin_density_per_1000 = float(match.group(2))
            cousin_density_per_1000 = float(match.group(3))
            analysis_data.append((n_gaps, twin_density_per_1000, cousin_density_per_1000))

    if not analysis_data:
        print("FATAL ERROR: No data rows found in the 'Density Trend Check' table.")
        return

    print(f"Successfully loaded {len(analysis_data)} data points from the Test 2 report.")
    print("-" * 80)
    
    # --- Run the Analysis ---
    print("\n" + "="*20 + " 'Constant of Proportionality' (C_2) Analysis " + "="*20)
    print(f"\n  N = The (p_n) index, not the value of p_n.")
    print(f"  Measured Density = Density per 1000 (from file) / 1000")
    print(f"  Theoretical Base = 1 / (ln(N))^2")
    print(f"  Constant (C_2) = Measured Density / Theoretical Base")
    
    print("\n" + "-" * 78)
    print(f"{'N Gaps':<12} | {'Measured (g_n=2)':<16} | {'Theoretical Base':<16} | {'Calculated Constant (C_2)':<25}")
    print("-" * 78)

    constants = []

    for n, twin_density_1000, _ in analysis_data:
        # We divide by 1000 because the "Density" in the file is "per 1000 primes"
        measured_density = twin_density_1000 / 1000.0
        theoretical_base = get_theoretical_density_base(n)
        
        if theoretical_base == 0:
            continue
            
        constant_c2 = measured_density / theoretical_base
        constants.append(constant_c2)
        
        print(f"{n:<12,} | {measured_density:<16.6f} | {theoretical_base:<16.6f} | {constant_c2:<25.4f}")

    print("-" * 78)

    # --- Final Conclusion ---
    print("\n\n" + "="*20 + " FINAL ANALYTIC CONCLUSION " + "="*20)
    
    if not constants:
        print("\n  [VERDICT: ANALYSIS FAILED]")
        print("  No constants were calculated.")
        return

    avg_constant = sum(constants) / len(constants)
    max_dev = max(constants) - min(constants)
    
    print(f"\n  Average Calculated Constant (C_2): {avg_constant:.4f}")
    print(f"  Max Deviation (Stability):         {max_dev:.4f}")

    # The *actual* Twin Prime Constant (2*C_2) is ~1.3203...
    # We are calculating C = (Density per 1) / (1/(ln N)^2).
    # The PNT for TPC is pi_2(x) ~ 2*C_2 * (x / (ln x)^2).
    # The density (d/dx) is pi_2'(x) ~ 2*C_2 / (ln x)^2.
    # So our "Calculated Constant" should be 2*C_2, which is ~1.32.
    
    if max_dev < 0.1: # If the constant is *extremely* stable
        print(f"\n  [VERDICT: HYPOTHESIS CONFIRMED. CONSTANT IS STABLE.]")
        print(f"  The 'Constant of Proportionality' is stable at approx {avg_constant:.4f}.")
        print(f"  This provides the final analytic link between the 100% PLR")
        print("  Theorem and the Hardy-Littlewood conjecture.")
        print(f"  The measured constant ({avg_constant:.4f}) is our 'PLR Constant' for TPC.")
    else:
        print(f"\n  [VERDICT: HYPOTHESIS FALSIFIED. CONSTANT IS UNSTABLE.]")
        print(f"  The calculated 'Constant' ({avg_constant:.4f}) is unstable")
        print(f"  (Max Deviation: {max_dev:.4f}).")
        print("  This implies the 1/(ln N)^2 model is too simple and")
        print("  our PLR data, while 100% accurate, follows a different analytic law.")

    print("=" * (50 + len(" FINAL ANALYTIC CONCLUSION ")))

if __name__ == "__main__":
    run_analytic_generalization()